1.	Create a python program to find duplicate files by content. User will input path and it will scan all directories, sub-         directories to find all duplicates files.
    Delete the found duplicate file.
    [Hint: use hashlib]


In [47]:
import os
import hashlib
d_path = 'D:/file/'
files_list = os.listdir(path = d_path)
files_list

['text1.txt', 'text2.txt']

In [48]:
list1=[]
for i in files_list:
    obj_f=open(d_path+i,'r')
    content = obj_f.read()
    obj_f.close()
    encode_content = content.encode()
    list1.append(hashlib.sha256(encode_content).hexdigest())

In [49]:
new_dict = dict(zip(files_list,list1))
new_dict

{'text1.txt': 'adf6ee86a5d6b7ad892bcbad505c6a598bb20bf6e1f3ee5637e6d278c6c0f937',
 'text2.txt': 'adf6ee86a5d6b7ad892bcbad505c6a598bb20bf6e1f3ee5637e6d278c6c0f937'}

In [50]:
type(new_dict.values())

dict_values

In [51]:
list1

['adf6ee86a5d6b7ad892bcbad505c6a598bb20bf6e1f3ee5637e6d278c6c0f937',
 'adf6ee86a5d6b7ad892bcbad505c6a598bb20bf6e1f3ee5637e6d278c6c0f937']

In [52]:
for i in range(len(list1)):
    if list1[i]==list1[i+1]:
        print(True)
    else:
        print(False)

True


IndexError: list index out of range

In [53]:
for i in new_dict:
    file2 = i
    new_path = os.path.join(d_path,file2)
#     print(new_path)
    os.remove(new_path)

D:/file/text1.txt
D:/file/text2.txt


2.	Generate random Password with exact length = 6, with minimum 1 uppercase, 2 lowercase, 2 digits, and remaining special         characters.
    Using these packages [random, strings]


In [ ]:
import random
import string
n1 = random.randint(0, 9)
n2 = random.randint(0, 9)
n3 = random.randint(0, 9)
l1 = random.choice(string.ascii_lowercase)
l2 = random.choice(string.ascii_lowercase)
u1 = random.choice(string.ascii_uppercase)
# print("Password {} ".format((u1)+(l1)+(l2)+ str(n1) + str(n2) + str(n3)))/
password = [str(n1),str(2),str(n3),l1,l2,u1]
random.shuffle(password)
new_pass = ""
for i in password:
    new_pass+=i
print(new_pass)

3.	Create 2D array and update the same 2D array provided that every prime number position should be replaced by cube of the       positioned number

In [72]:
import numpy as np
import sympy
arr1=np.arange(0,9).reshape(3,3)
shape = arr1.reshape(9)
print(shape)
for i in range(len(shape)):
    if sympy.isprime(shape[i]):
        shape[i]=shape[i]**3
        
new=shape.reshape(3,3)
print(new)

[0 1 2 3 4 5 6 7 8]
[[  0   1   8]
 [ 27   4 125]
 [  6 343   8]]


4.	Python program to get the sum of every cubed value and its previous integer. 

In [70]:
# import numpy as np
# import sympy
# prime = []
# arr1=np.arange(0,9).reshape(3,3)
# shape = arr1.reshape(9)
# for i in range(len(shape)):
#     if sympy.isprime(shape[i]):
#         shape[i]=shape[i]**3
#         prime.append(shape[i])

# print(prime)
# new_prime=[]
# for i in range(len(prime)):
#     new_prime.append(prime[i]-1)
    
# print(new_prime)
# sum1 = sum(prime)
# sum2 = sum(new_prime)
# print(sum1+sum2)

[8, 27, 125, 343]
[7, 26, 124, 342]
1002


In [74]:
import numpy as np
import sympy
prime = []
arr1=np.arange(0,9).reshape(3,3)
shape = arr1.reshape(9)
for i in range(len(shape)):
    if sympy.isprime(shape[i]):
        shape[i]=shape[i]**3
        shape[i]=shape[i] + shape[i-1]
        
new_shape=shape.reshape(3,3)
print(new_shape)

[[  0   1   9]
 [ 36   4 129]
 [  6 349   8]]


5.	Given two arrays, find their intersection. Examples:
    Input:  arr1[] = [1, 3, 4, 5, 7]
            arr2[] = [2, 3, 5, 6]

In [72]:
import numpy as np
arr1 = [1,3,4,5,7]
arr2 = [2,3,5,6]
A1=np.array(arr1)
A2=np.array(arr2)
print(np.intersect1d(A1,A2))

[3 5]


6.	Create a 7 x 7  2D array having only multiples of 7. And return the last element of the same.

In [71]:
x=np.array([i*7 for i in range(1,7*7+1)]).reshape(7,7)
x[-1,-1]

343

7.	Checker Board Patten using Numpy:
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]

In [ ]:
import numpy as np
n = int(input("enter size"))
mat = np.ones((n,n),dtype=int)
mat[1::2,0::2] = 0
mat[0::2,1::2] = 0

print(mat)

8.	Create a given Matrix:
    ['A', 'B', 'C', 'D'],
    ['E', 'F', 'G', 'H'],
    ['I', 'J', 'K', 'L'],
    ['M', 'N', 'O', 'P'],
    ['Q', 'R', 'S', 'T'],
    ['U', 'V', 'W', 'X']

   Replace all the vowels by np.nan
   A, E, I, O U  -- >  np.nan
   Return the count of the missing values


In [55]:
import numpy as np
arr = np.array([['A','B','C','D'],
                ['E','F','G','H'],
                ['I','J','K','L'],
                ['M','N','O','P'],
                ['Q','R','S','T'],
                ['U','V','W','X']]
)

In [56]:
lis = arr.tolist()
for i in range(len(lis)):
    for j in range(len(lis[i])):
        if lis[i][j]=='A' or lis[i][j]=='E' or lis[i][j]=='I' or lis[i][j]=='O' or lis[i][j]=='U':
             lis[i][j] = np.nan
                
print(np.array(lis)) 

[['nan' 'B' 'C' 'D']
 ['nan' 'F' 'G' 'H']
 ['nan' 'J' 'K' 'L']
 ['M' 'N' 'nan' 'P']
 ['Q' 'R' 'S' 'T']
 ['nan' 'V' 'W' 'X']]
