In [2]:
# Numerical Python  (numpy alias as np)
import numpy as np

In [3]:
print(np.__version__)

1.21.5


### Numpy Array

In [4]:
list1 = [1,2,3,4,5,6,7,8,9]
np.array(list1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# N-Dimensional Array
type(np.array(list1))

numpy.ndarray

In [8]:
arr1=np.array(list1)

In [9]:
arr1.dtype

dtype('int32')

In [11]:
arr1.shape

(9,)

In [12]:
arr1.ndim

1

In [14]:
print(arr1.itemsize)

4


In [15]:
print(arr1.nbytes)

36


### Array Operations
    * Simple Array Math Operations

* Why Numpy are better than lists

In [26]:
list1 = [10,20,30,40,50,60,70,80,90]
list2 = [2,4,3,6,5,6,7,8,9]
list3 =[]
for i in range (len(list1)):
    list3.append(list1[i]/list2[i])
    
print(list3)

[5.0, 5.0, 10.0, 6.666666666666667, 10.0, 10.0, 10.0, 10.0, 10.0]


In [30]:
arr1 =np.array([10,20,30,40,50,60,70,80,90])
arr2 =np.array([2,4,3,6,5,6,7,8,9])
# element by element division
arr1/arr2

array([ 5.        ,  5.        , 10.        ,  6.66666667, 10.        ,
       10.        , 10.        , 10.        , 10.        ])

In [32]:
# generates numpy array using arange(start,stop,step)
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Types of Numpy Array

In [48]:
# dtype = data type with size
# int8, int16, int32, int64
# -128 to +127
arr1 = np.array([10,12,15,16,18,20,25,256], dtype = 'int8')
print(arr1)

[10 12 15 16 18 20 25  0]


In [41]:
arr2 = np.array([10.,12.,15.,16.,18.,20.,25.], dtype = 'float16')
print(arr2)

[10. 12. 15. 16. 18. 20. 25.]


In [43]:
list1.__sizeof__()

136

In [44]:
arr1.__sizeof__()

112

In [51]:
arr3 = np.array([10,20,30,40,50,60,70,80,90])
arr3.nbytes

36

In [111]:
# create a list with range 1,1000000
#list version
list_1=list(range(1,100000))
def list_version(list_1):
    add=0
    for i in list_1:
        add+=i   
        
    print(add)
list_version(list_1)

4999950000


In [110]:
#numpy version
arr_1=np.arange(1,100000)
def numpy_version(arr_1):
    add= 0
    add=arr_1.sum()
    print(add)
numpy_version(arr_1)        

704982704


In [106]:
import time
size = 100000
def list_version():
    start = time.time()
    x=range(size)
    y=range(size)
    #element by element addtion
    Z=[x[i]+y[i] for i in range(len(x))]
    return time.time() - start

def numpy_version():
    start = time.time()
    x=np.arange(size)
    y=np.arange(size)
    z=x+y
    return time.time() - start

In [107]:
list_version()
    

0.056116580963134766

In [109]:
numpy_version()

0.005239963531494141

#### Two Dimensional Array


In [116]:
arr2 = np.array([[0,1,2,3,4,5,6,7],
        [10,11,12,13,14,15,16,17]])

In [117]:
arr2.shape

(2, 8)

In [118]:
# shape[0] = rows, shape[1]=columns
arr2.shape[0],arr2.shape[1]

(2, 8)

In [119]:
#returns dimensions
print(arr2.ndim)

2


In [121]:
# slicing in numpy array

#displays first row
arr2[0]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [127]:
#displays single row element
print(arr2[1][3])
print(arr2[1,3])

13
13


In [129]:
#indexing 2D array 
# first -1 is for row and the next -1 is for columns
arr2[-1,-1] 

17

In [131]:
#update an numpy array
arr2[-1,-1]=15
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15, 16, 15]])

In [135]:
# slicing to 2D array
#displays all rows and columns except last row and last column
arr2[:-1,:-1]

array([[0, 1, 2, 3, 4, 5, 6]])

### Three Dimensional Array

In [140]:
# 3D Array -> Tensor
arr3 = np.array([[[0,1,2,3,4,5,6,7],
                  [10,11,12,13,14,15,16,17]],
                 
                 [[0,1,2,3,4,5,6,7],                 
                  [10,11,12,13,14,15,16,17]],
                 
                  [[0,1,2,3,4,5,6,7],
                  [10,11,12,13,14,15,16,17]]])

In [154]:
arr3

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [10, 11, 12, 13, 14, 15, 16, 17]],

       [[ 0,  1,  2,  3,  4,  5,  6,  7],
        [10, 11, 12, 13, 14, 15, 16, 17]],

       [[ 0,  1,  2,  3,  4,  5,  6,  7],
        [10, 11, 12, 13, 14, 15, 16, 17]]])

In [142]:
# Rank, Rows, Columns
arr3.shape

(3, 2, 8)

In [146]:
arr3[1,1,4]

14

In [144]:
# shows length of all elements (3*2*8)
# size = number of elements present in a array
arr3.size

48

#### Empty array & fill wth some constant value

In [148]:
arr4 = np.empty(6,dtype='float16')
arr4

array([ 4.560e+02, -3.816e+00,  3.403e-05,  0.000e+00,  0.000e+00,
        0.000e+00], dtype=float16)

In [150]:
arr5 = np.arange(0,36).reshape(6,6)
arr5

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [156]:
arr5 = np.arange(2,38).reshape(4,3,3)
arr5

array([[[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]],

       [[29, 30, 31],
        [32, 33, 34],
        [35, 36, 37]]])

#### Reverse of array

In [110]:
arr6 = np.arange(50)
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [111]:
arr6[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [114]:
arr6 = np.arange(0,36).reshape(6,6)
arr6

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [115]:
# ud() -> up/down
np.flipud(arr6)

array([[30, 31, 32, 33, 34, 35],
       [24, 25, 26, 27, 28, 29],
       [18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5]])

In [116]:
# lr() -> left/right
np.fliplr(arr6)

array([[ 5,  4,  3,  2,  1,  0],
       [11, 10,  9,  8,  7,  6],
       [17, 16, 15, 14, 13, 12],
       [23, 22, 21, 20, 19, 18],
       [29, 28, 27, 26, 25, 24],
       [35, 34, 33, 32, 31, 30]])

In [117]:
np.flip(arr6)

array([[35, 34, 33, 32, 31, 30],
       [29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

Create an array using methods
    * np.ones()
    * np.zeros()

In [159]:
#shape 3 rows,  6 columns
np.zeros((3,6),dtype = 'float16')

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float16)

* identity Matrix
    * Generate a N x N Identity matrix. The default matrix dtype is float64
    *Diagonal values are 1, non diagonal values are 0
    

In [160]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [162]:
np.identity(7,dtype='int8')

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]], dtype=int8)

In [164]:
# (start, stop, elements)
# equally spaced
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [46]:
import numpy as np
n = int(input("enter size"))
pat = np.ones((n,n),dtype=int)
pat[1:-1,1:-1] =0
# pat[0]=1
# pat[-1]=1
# pat[:,0]=1
# pat[:,-1]=1
print(pat)


enter size5
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [48]:
import numpy as np
n = int(input("enter size"))
mat = np.ones((n,n),dtype=int)
mat[1::2,0::2] = 0
mat[0::2,1::2] = 0

print(mat)

enter size7
[[1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]]


#### Null Values

In [49]:
# not a nan
np.nan

nan

In [52]:
arr9 = np.ones((5,5))
arr9[1::2,0::2] = np.nan
arr9[0::2,1::2] = np.nan

print(arr9)

[[ 1. nan  1. nan  1.]
 [nan  1. nan  1. nan]
 [ 1. nan  1. nan  1.]
 [nan  1. nan  1. nan]
 [ 1. nan  1. nan  1.]]


In [54]:
# isnan() - returns boolen value, True for missing data, False for not-missing data
np.isnan(arr9)

array([[False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False]])

In [55]:
# np.count_nonzero() cpunt false/0 values
np.count_nonzero(~np.isnan(arr9))

13

In [4]:
import numpy as np
arr = np.array([['A','B','C','D'],
                ['E','F','G','H'],
                ['I','J','K','L'],
                ['M','N','O','P'],
                ['Q','R','S','T'],
                ['U','V','W','X']]
)


In [5]:
lis = arr.tolist()
lis

[['A', 'B', 'C', 'D'],
 ['E', 'F', 'G', 'H'],
 ['I', 'J', 'K', 'L'],
 ['M', 'N', 'O', 'P'],
 ['Q', 'R', 'S', 'T'],
 ['U', 'V', 'W', 'X']]

In [9]:
for i in range(len(lis)):
    for j in range(len(lis[i])):
        if lis[i][j]=='A' or lis[i][j]=='E' or lis[i][j]=='I' or lis[i][j]=='O' or lis[i][j]=='U':
             lis[i][j] = np.nan
                
print(np.array(lis)) 

[['nan' 'B' 'C' 'D']
 ['nan' 'F' 'G' 'H']
 ['nan' 'J' 'K' 'L']
 ['M' 'N' 'nan' 'P']
 ['Q' 'R' 'S' 'T']
 ['nan' 'V' 'W' 'X']]


### Numpy
    * Array calculation method

In [121]:
arr3= np.array([[1,2,3],
                [4,5,6]]
              )
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [123]:
arr3.sum()

21

In [124]:
# row1+row2
# apply sum along 0th axis
arr3.sum(axis=0)

array([5, 7, 9])

In [126]:
# axis =1 (sum of all columns)
# apply sum along 1st axis
arr3.sum(axis=1)

array([ 6, 15])

In [129]:
#[0.,0.,0.,1.,0.,0.,0.]
arr4 = [0.,0.,0.,1.,0.,0.,0.]
# returns index of the maximum value along axis
np.argmax(arr4)

3

In [138]:
arr5 = np.arange(1,37).reshape(6,6)
arr5

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [139]:
np.argmax(arr5,axis=0)

array([5, 5, 5, 5, 5, 5], dtype=int64)

In [140]:
np.argmax(arr5,axis=1)

array([5, 5, 5, 5, 5, 5], dtype=int64)

In [141]:
np.argmax(arr5)

35

### Statistical Analysis on Array

In [143]:
arr_6 = np.array([[1,2,4],
                  [5,7,8]])
# average = (sum of values)/(number of elements)
arr_6.mean()

4.5

In [145]:
arr_6 = np.array([1,2,4,7,8,11,13])
np.median(arr_6)

7.0

In [147]:
arr_6 = np.array([1,2,4,8,11,13])
# median of two central values
np.median(arr_6)

6.0

In [148]:
#standard deviation of array
np.std(arr_6)

4.5

In [150]:
#variance of an array
np.var(arr_6)

20.25